export const DRIVE_SET_AVAILABLE = 'DRIVE_SET_AVAILABLE';
export const DRIVE_SELECT = 'DRIVE_SELECT';
export const DRIVE_SELECTOR_SHOW = 'DRIVE_SELECTOR_SHOW';
export const DRIVE_SELECTOR_HIDE = 'DRIVE_SELECTOR_HIDE';
export const DRIVE_BURN_PROGRESS = 'DRIVE_BURN_PROGRESS';
export const DRIVE_BURN_ERROR = 'DRIVE_BURN_ERROR';
export const DRIVE_BURN_IMAGE_COMPLETE = 'DRIVE_BURN_IMAGE_COMPLETE';
export const DRIVE_BURN_FINISHED = 'DRIVE_BURN_FINISHED';

export const STATUS_NOTHING = 'STATUS_NOTHING';
export const STATUS_BURNING_IMAGE = 'STATUS_BURNING_IMAGE';
export const STATUS_BURNING_EXTRA = 'STATUS_BURNING_EXTRA';
export const STATUS_ERROR = 'STATUS_ERROR';
export const STATUS_COMPLETE = 'STATUS_COMPLETE';
