export const DOWNLOAD_CHECK = 'DOWNLOAD_CHECK';
export const DOWNLOAD_START = 'DOWNLOAD_START';
export const DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS';
export const DOWNLOAD_COMPLETE = 'DOWNLOAD_COMPLETE';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';
export const DOWNLOAD_START_CHECK = 'DOWNLOAD_START_CHECK';

export const DOWNLOAD_TYPE_WORDPRESS = 'DOWNLOAD_TYPE_WORDPRESS';
export const DOWNLOAD_TYPE_RASPBIAN = 'DOWNLOAD_TYPE_RASPBIAN';

export const DOWNLOAD_STATUS_CHECKING = 'DOWNLOAD_STATUS_CHECKING';
export const DOWNLOAD_STATUS_DOWNLOADING = 'DOWNLOAD_STATUS_DOWNLOADING';
export const DOWNLOAD_STATUS_COMPLETE = 'DOWNLOAD_STATUS_COMPLETE';
export const DOWNLOAD_STATUS_ERROR = 'DOWNLOAD_STATUS_ERROR';
