export const CONFIG_GOTO_STAGE = 'CONFIG_GOTO_STAGE';
export const CONFIG_CHANGE_SETTING = 'CONFIG_CHANGE_SETTING';
export const CONFIG_CLEAR_ALL = 'CONFIG_CLEAR_ALL';
export const CONFIG_PICK_SSH = 'CONFIG_PICK_SSH';

export const STAGE_INTRO = 'STAGE_INTRO';
export const STAGE_GATHER_BASIC = 'STAGE_GATHER_BASIC';
export const STAGE_GATHER_ADVANCED = 'STAGE_GATHER_ADVANCED';
export const STAGE_SELECT_DRIVE = 'STAGE_SELECT_DRIVE';
export const STAGE_BURN = 'STAGE_BURN';
export const STAGE_DOWNLOAD = 'STAGE_DOWNLOAD';
export const STAGE_COMPLETE = 'STAGE_COMPLETE';
